// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfOnNdIUTasLhzLDMPjAFvT9ibH-8oAY',
    appId: '1:745084510738:web:fd329aac3645d43e846ecb',
    messagingSenderId: '745084510738',
    projectId: 'kantin-e4295',
    authDomain: 'kantin-e4295.firebaseapp.com',
    storageBucket: 'kantin-e4295.appspot.com',
    measurementId: 'G-9FB8FJMQ4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKvpZEM-lUTCi_f3lZYacD7qI9GjNDQY',
    appId: '1:745084510738:android:fdca98200772cb0f846ecb',
    messagingSenderId: '745084510738',
    projectId: 'kantin-e4295',
    storageBucket: 'kantin-e4295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpr3z1r7gFfkKA-kYI71Fxe7-OUlC6dB4',
    appId: '1:745084510738:ios:9bfa4c95c92cf234846ecb',
    messagingSenderId: '745084510738',
    projectId: 'kantin-e4295',
    storageBucket: 'kantin-e4295.appspot.com',
    iosBundleId: 'com.example.kantin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpr3z1r7gFfkKA-kYI71Fxe7-OUlC6dB4',
    appId: '1:745084510738:ios:9bfa4c95c92cf234846ecb',
    messagingSenderId: '745084510738',
    projectId: 'kantin-e4295',
    storageBucket: 'kantin-e4295.appspot.com',
    iosBundleId: 'com.example.kantin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjfOnNdIUTasLhzLDMPjAFvT9ibH-8oAY',
    appId: '1:745084510738:web:c2ccd027e70a1ece846ecb',
    messagingSenderId: '745084510738',
    projectId: 'kantin-e4295',
    authDomain: 'kantin-e4295.firebaseapp.com',
    storageBucket: 'kantin-e4295.appspot.com',
    measurementId: 'G-TQ21NHVVDP',
  );

}